### ISSUE TITLE
Dual headlines

### ISSUE THREAD

**Issue by Henning-Klatt** [CyberSchoolSystem/CyberSchoolSystem-server#7]
2 headlines.
"Permission denied"

**Comment by FabianGeiselhart** [comment]
Fix in defaultLayout

**Comment by Henning-Klatt** [comment]
Do you post it as a title and msg?

**Comment by FabianGeiselhart** [comment]
Nope. But yesod posts a title and i do too.

**Comment by Henning-Klatt** [comment]
So can you just remove your title and let yesod do its job?
